import { Dimensions, Platform, StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    navbar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: Platform.OS === 'ios' ? 60 : 50,
        paddingBottom: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.border,
    },
    welcomeText: {
        color: colors.textMuted,
        fontSize: 10,
        fontWeight: '600',
        letterSpacing: 1.5,
    },
    userName: {
        color: colors.text,
        fontSize: 18,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    logoutBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scrollContent: {
        padding: 24,
        paddingBottom: 100,
    },
    garageSection: {
        marginBottom: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        color: colors.textMuted,
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 1.2,
    },
    addVehIcon: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
    },
    vehiclesScroll: {
        gap: 8,
    },
    vehTab: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        height: 38,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
        marginRight: 8,
    },
    vehTabActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    vehTabIcon: {
        marginRight: 8,
    },
    vehTabText: {
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: '600',
    },
    vehTabTextActive: {
        color: colors.background,
    },
    mainDashboard: {
        width: '100%',
    },
    carGraphicContainer: {
        alignItems: 'center',
        paddingVertical: 24,
        backgroundColor: colors.carBgContainer,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.surfaceCard,
        marginBottom: 24,
        width: '100%',
    },
    carChassis: {
        width: 160,
        height: 80,
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    wheel: {
        width: 28,
        height: 14,
        backgroundColor: colors.darkGray,
        borderWidth: 1,
        borderColor: colors.mediumGray,
        borderRadius: 2,
        position: 'absolute',
    },
    wheelFL: { top: 0, left: 16 },
    wheelFR: { top: 0, right: 16 },
    wheelRL: { bottom: 0, left: 16 },
    wheelRR: { bottom: 0, right: 16 },
    carBody: {
        width: 120,
        height: 48,
        borderWidth: 1,
        borderColor: colors.carChassisBorder,
        borderRadius: 16,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    carBodyPlate: {
        color: colors.carChassisBorder,
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 1,
    },
    carDetails: {
        alignItems: 'center',
    },
    carTitle: {
        color: colors.text,
        fontSize: 22,
        fontWeight: '700',
    },
    carMeta: {
        color: colors.textMuted,
        fontSize: 12,
        marginTop: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    carOdometer: {
        color: colors.text,
        fontSize: 26,
        fontWeight: '300',
        marginTop: 12,
        letterSpacing: 1,
    },
    kmUnit: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.textMuted,
    },
    statsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    statCard: {
        width: (width - 60) / 2,
        paddingVertical: 12,
    },
    statLabel: {
        color: colors.textMuted,
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 1.2,
    },
    statValue: {
        color: colors.text,
        fontSize: 22,
        fontWeight: '700',
        marginVertical: 4,
    },
    statSubText: {
        color: colors.textSecondary,
        fontSize: 10,
    },
    criticalAlertBanner: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: colors.error,
        borderRadius: 8,
        padding: 16,
        marginBottom: 24,
        width: '100%',
    },
    alertHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        gap: 8,
    },
    alertBannerTitle: {
        color: colors.error,
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1.2,
    },
    alertBannerText: {
        color: colors.text,
        fontSize: 13,
        marginTop: 4,
        lineHeight: 18,
    },
    actionMenu: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingVertical: 16,
        marginBottom: 24,
        width: '100%',
    },
    actionBtn: {
        alignItems: 'center',
        flex: 1,
    },
    actionIconBg: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    actionBtnText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '600',
    },
    statusRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    statusInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    statusLabel: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '500',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    statusBadgeText: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '700',
        backgroundColor: colors.border,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
        overflow: 'hidden',
    },
    noVehicleContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 80,
    },
    noVehicleText: {
        color: colors.textMuted,
        fontSize: 14,
        textAlign: 'center',
    },
    profileModalScroll: {
        paddingBottom: 20,
    },
    profileAvatarSection: {
        alignItems: 'center',
        marginBottom: 24,
    },
    profileAvatarCircle: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    profileUserEmailLabel: {
        fontSize: 14,
        color: colors.textSecondary,
    },
    profileSaveBtn: {
        marginTop: 16,
    },
    profileDivider: {
        height: 0.5,
        backgroundColor: colors.border,
        marginVertical: 24,
    },
    profileDangerZoneTitle: {
        fontSize: 11,
        fontWeight: '700',
        color: colors.textMuted,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        marginBottom: 12,
    },
    profileActionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 14,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.border,
    },
    profileActionLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    profileActionCenter: {
        width: '100%',
        padding: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileActionText: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
    },
    profileActionChevron: {
        fontSize: 14,
        color: colors.textSecondary,
    },
    obdStatusBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: colors.surfaceCard,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginBottom: 16,
    },
    obdStatusLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    obdStatusTitle: {
        color: colors.text,
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 1.2,
    },
    obdStatusAction: {
        backgroundColor: colors.border,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 4,
    },
    obdStatusActionText: {
        color: colors.text,
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 1,
    },
    obdTelemetryContainer: {
        marginBottom: 16,
    },
    obdTelemetryGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    obdTelemetryCard: {
        flex: 1,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        padding: 12,
    },
    obdTelemetryCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 6,
    },
    obdTelemetryCardLabel: {
        color: colors.textMuted,
        fontSize: 10,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    obdTelemetryCardValue: {
        color: colors.text,
        fontSize: 18,
        fontWeight: '700',
    },
    obdTelemetryCardSubText: {
        color: colors.textSecondary,
        fontSize: 10,
        marginTop: 2,
    },
    liveBadge: {
        position: 'absolute',
        top: 12,
        right: 12,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(76, 175, 80, 0.12)',
        borderColor: colors.success,
        borderWidth: 0.5,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    liveDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: colors.success,
        marginRight: 6,
    },
    liveText: {
        color: colors.success,
        fontSize: 8,
        fontWeight: '800',
        letterSpacing: 1,
    },
});
