import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: 60,
        paddingBottom: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.border,
    },
    backBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: -10,
    },
    headerTitle: {
        color: colors.text,
        fontSize: 20,
        fontWeight: '700',
    },
    headerAddBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.secondary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    formScroll: {
        padding: 24,
        paddingBottom: 60,
    },
    listScroll: {
        padding: 24,
        paddingBottom: 100,
    },
    vehSubtitle: {
        color: colors.textMuted,
        fontSize: 14,
        marginBottom: 20,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    errorText: {
        color: colors.error,
        fontSize: 14,
        marginBottom: 16,
        fontWeight: '500',
    },
    fieldLabel: {
        color: colors.textMuted,
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 1.2,
        marginBottom: 8,
    },
    typeSelectorGrid: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 20,
    },
    typeBtn: {
        flex: 1,
        height: 44,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
    },
    typeBtnActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    typeBtnText: {
        color: colors.textMuted,
        fontSize: 14,
        fontWeight: '600',
    },
    typeBtnTextActive: {
        color: colors.background,
    },
    rowInputs: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    uploadBox: {
        height: 80,
        borderWidth: 1,
        borderColor: colors.border,
        borderStyle: 'dashed',
        borderRadius: 4,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        marginBottom: 24,
    },
    uploadBoxText: {
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: '500',
    },
    imagePreviewContainer: {
        marginBottom: 24,
        alignItems: 'center',
    },
    imagePreview: {
        width: '100%',
        height: 160,
        borderRadius: 4,
        backgroundColor: colors.border,
    },
    removeImageBtn: {
        marginTop: 8,
        padding: 8,
    },
    removeImageText: {
        color: colors.error,
        fontSize: 13,
        fontWeight: '700',
    },
    submitBtn: {
        marginTop: 12,
    },
    cardHeaderRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    badge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 2,
        borderWidth: 0.5,
    },
    badgePreventive: {
        borderColor: colors.text,
        backgroundColor: 'transparent',
    },
    badgeCorrective: {
        borderColor: colors.error,
        backgroundColor: 'transparent',
    },
    badgeText: {
        fontSize: 9,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    badgeTextPreventive: {
        color: colors.text,
    },
    badgeTextCorrective: {
        color: colors.error,
    },
    cardBody: {
        marginTop: 8,
    },
    costRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: colors.surface,
        padding: 12,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: colors.border,
        marginBottom: 12,
    },
    costItem: {
        flex: 1,
    },
    costItemTotal: {
        alignItems: 'flex-end',
    },
    costLabel: {
        color: colors.textMuted,
        fontSize: 10,
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    costValue: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '600',
        marginTop: 2,
    },
    costLabelTotal: {
        color: colors.error,
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    costValueTotal: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '700',
        marginTop: 2,
    },
    detailBox: {
        marginTop: 8,
        paddingTop: 8,
        borderTopWidth: 0.5,
        borderTopColor: colors.border,
    },
    detailLabel: {
        color: colors.textSecondary,
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 0.5,
        marginBottom: 4,
    },
    detailText: {
        color: colors.textMuted,
        fontSize: 13,
        lineHeight: 18,
    },
    attachmentBox: {
        marginTop: 12,
        paddingTop: 8,
        borderTopWidth: 0.5,
        borderTopColor: colors.border,
    },
    attachmentThumb: {
        width: 120,
        height: 90,
        borderRadius: 4,
        backgroundColor: colors.border,
        marginTop: 4,
    },
    deleteBtn: {
        padding: 4,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 80,
        paddingHorizontal: 20,
    },
    emptyText: {
        color: colors.textMuted,
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
    },
    editBtn: {
        padding: 4,
    },
    timestampText: {
        color: colors.textSecondary,
        fontSize: 10,
        fontStyle: 'italic',
    },
    sortContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        backgroundColor: colors.surface,
        padding: 10,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: colors.border,
    },
    sortGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    sortLabel: {
        color: colors.textSecondary,
        fontSize: 9,
        fontWeight: '700',
        letterSpacing: 0.5,
        marginRight: 4,
    },
    sortBtn: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 3,
        borderWidth: 0.5,
        borderColor: colors.border,
        backgroundColor: 'transparent',
    },
    sortBtnActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    sortBtnText: {
        color: colors.textSecondary,
        fontSize: 11,
        fontWeight: '600',
    },
    sortBtnTextActive: {
        color: colors.background,
        fontWeight: '700',
    },
    sortOrderBtn: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 3,
        borderWidth: 0.5,
        borderColor: colors.border,
        backgroundColor: 'transparent',
    },
    sortOrderBtnText: {
        color: colors.text,
        fontSize: 11,
        fontWeight: '600',
    },
});
